name: Build and Release for Windows and Ubuntu

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.6'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ssh-keyword-cli.exe ./cmd/main.go

      - name: Build for Ubuntu
        run: GOOS=linux GOARCH=amd64 go build -o ssh-keyword-cli ./cmd/main.go

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: ssh-keyword-cli.exe

      - name: Upload Ubuntu Binary
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binary
          path: ssh-keyword-cli

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          body: "Description of the changes and assets included in this release."

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ssh-keyword-cli.exe
          asset_name: ssh-keyword-cli.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset for Ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ssh-keyword-cli
          asset_name: ssh-keyword-cli
          asset_content_type: application/octet-stream
