name: Build and Test for Windows and Ubuntu

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '1.21.6'

      - name: Run Tests
        run: go test ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '1.21.6'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ssh-keyword.exe ./cmd/main.go

      - name: Build for Ubuntu
        run: GOOS=linux GOARCH=amd64 go build -o ssh-keyword-linux-amd64 ./cmd/main.go

      - name: Upload Windows Binary
        uses: actions/upload-artifact@main
        with:
          name: windows-binary
          path: ssh-keyword.exe

      - name: Upload Ubuntu Binary
        uses: actions/upload-artifact@main
        with:
          name: ubuntu-binary
          path: ssh-keyword-linux-amd64