name: Build for Windows and Ubuntu

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.6'

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o ssh-keyword-cli.exe ./cmd/main.go

      - name: Build for Ubuntu
        run: GOOS=linux GOARCH=amd64 go build -o ssh-keyword-cli ./cmd/main.go

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: ssh-keyword-cli.exe

      - name: Upload Ubuntu Binary
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binary
          path: ssh-keyword-cli
