name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o ssh-keyword-cli.exe ./cmd/main.go
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-binary
        path: ssh-keyword-cli.exe
